on: push

jobs:
    built-in-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: CMake build
              run: |
                  ls
                  cd ${{ github.workspace }}
                  ls
                  mkdir build
                  cd build 
                  cmake --version
                  cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ${{ github.workspace }} -B ${{ github.workspace }}/build
                  ls
            - name: CMake CMake install
              run: |
                  cd ${{ github.workspace }}/build
                  ls
                  cmake --build ${{ github.workspace }}/build --target calendar -- -j 18
                  ls
                  ./calendar.exe -s

            # - run: ls
            # - run: cmake --version
            # - run: make --version
            # - run: cmake ./
            # - run: make

    built-in-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: CMake build
              run: |
                  ls
                  cd ${{ github.workspace }}
                  ls
                  mkdir build
                  cd build 
                  cmake --version
                  cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -S ${{ github.workspace }} -B ${{ github.workspace }}/build
                  ls
              shell: pwsh
            - name: CMake CMake install
              run: |
                  cd ${{ github.workspace }}/build
                  ls
                  cmake --build ${{ github.workspace }}/build --target calendar -- -j 18
                  ls
                  ./calendar.exe -s
              shell: pwsh
