on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: "0 0 * * *" # every day
    workflow_dispatch:

jobs:
    push_some_info:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: push some info
              run: |
                  cd ${{ github.workspace }}
                  python3 ./push.py

    built-in-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: CMake build
              run: |
                  cd ${{ github.workspace }}
                  mkdir build
                  cd build 
                  cmake --version
                  cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ${{ github.workspace }} -B ${{ github.workspace }}/build
              shell: bash
            - name: CMake CMake install
              run: |
                  cd ${{ github.workspace }}/build
                  cmake --build ${{ github.workspace }}/build --target calendar -- -j 18
                  ./calendar -s
              shell: bash

    built-in-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: CMake build
              run: |
                  cd ${{ github.workspace }}
                  mkdir build
                  cd build 
                  cmake --version
                  cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -S ${{ github.workspace }} -B ${{ github.workspace }}/build
              shell: pwsh
            - name: CMake CMake install
              run: |
                  cd ${{ github.workspace }}/build
                  cmake --build ${{ github.workspace }}/build --target calendar -- -j 18
                  ./calendar.exe -s
              shell: pwsh
