on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - run: pwd
        - run: ls
        - run: node --version
        - run: cmake --version
        - run: make --version
    job2:
        runs-on: windows-latest
        steps:
        - run: node --version
        - run: cmake --version
        - run: make --version
    