on: push

jobs:
    built-in-ubuntu: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: pwd
        - run: ls
        - run: cmake --version
        - run: make --version
        - run: cmake ./
        - run: make
    
    built-in-windows: 
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
        - run: pwd
        - run: ls
        - run: cmake --version
        - run: make --version
        - run: cmake ./
        - run: make
    