on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    built-in-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: print some info
              run: |
                  cd ${{ github.workspace }}
                  echo "github.actor: ${{ github.actor }}"
                  
              shell: bash
    
